# -*- coding: utf-8 -*-
"""Project 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xVvweVtowykZvIQUKqLIHF-QDk3afput
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

data = pd.read_csv("/content/superstore.csv")

print(data.head())
print(data.info())

data["Order Date"] = pd.to_datetime(data["Order Date"])
print(data.isnull().sum())

data["Month"] = data["Order Date"].dt.month
data["Year"] = data["Order Date"].dt.year

total_revenue = data["Sales"].sum()
print("Total Revenue:", round(total_revenue, 2))

avg_order_value = data.groupby("Order ID")["Sales"].sum().mean()
print("Average Order Value:", round(avg_order_value, 2))

top_regions = data.groupby("Region")["Sales"].sum().sort_values(ascending=False)
print(top_regions)

top_products = data.groupby("Product Name")["Sales"].sum().sort_values(ascending=False).head(10)

plt.figure()
top_products.plot(kind="bar")
plt.title("Top 10 Products by Sales")
plt.ylabel("Sales")
plt.xticks(rotation=75)
plt.tight_layout()
plt.show()

monthly_sales = data.groupby("Month")["Sales"].sum()

plt.figure()
monthly_sales.plot(marker="o")
plt.title("Monthly Sales Trend")
plt.xlabel("Month")
plt.ylabel("Sales")
plt.grid(True)
plt.show()

plt.figure()
top_regions.plot(kind="bar")
plt.title("Sales by Region")
plt.ylabel("Sales")
plt.xticks(rotation=0)
plt.show()

sales_trend = data.groupby("Order Date")["Sales"].sum()

plt.figure(figsize=(10,4))
sales_trend.plot()
plt.title("Sales Trend Over Time")
plt.ylabel("Sales")
plt.show()

!pip install fpdf2

from fpdf import FPDF

pdf = FPDF()
pdf.add_page()

pdf.set_font("Arial", "B", 14)
pdf.cell(0, 10, "Sales Analysis Summary", ln=True)

pdf.set_font("Arial", size=11)
pdf.multi_cell(0, 8, f"""
Total Revenue: {round(total_revenue,2)}
Average Order Value: {round(avg_order_value,2)}

Top Region:
{top_regions.idxmax()}

Key Insights:
- Strong seasonal trends
- Top products dominate revenue
- Regional sales imbalance

Recommendations:
- Focus on high-demand products
- Increase marketing during peak months
- Expand in top regions
""")

pdf.output("Sales_Analysis_Summary.pdf")